version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:14
    
    steps:
      - checkout

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn add eslint eslint-config-react-app
      - run: yarn run eslint ./src

  test-and-build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "package.json"}}

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
              paths:
                    - node_modules
              key: deps-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn build
  
  audit:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run: yarn audit

workflows:
  node-tests:
    jobs:
      - lint
      - test-and-build
      - audit