# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test-and-build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install
      - run: yarn test
      - run: yarn build

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  node-tests: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-and-build
